# Generated by Django 6.0.6 on 2026-06-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('first_name', models.CharField(max_length=140, verbose_name='نام')),
                ('last_name', models.CharField(max_length=140, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('request_type', models.CharField(choices=[('product_question', 'سؤال درباره محصول'), ('order_followup', 'پیگیری سفارش'), ('wholesale', 'خرید عمده'), ('consultation', 'مشاوره خرید'), ('other', 'سایر')], default='other', max_length=40, verbose_name='نوع درخواست')),
                ('subject', models.CharField(max_length=180, verbose_name='موضوع پیام')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('in_progress', 'در حال بررسی'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته شده')], db_index=True, default='new', max_length=30, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'درخواست تماس',
                'verbose_name_plural': 'درخواست\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
    ]
