# Generated by Django 6.0.6 on 2026-06-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('available', 'موجود'), ('unavailable', 'نا موجود')], default='available', max_length=30, verbose_name='وضعیت موجودی'),
        ),
    ]
