# Generated by Django 6.0.6 on 2026-06-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_order_counter_product_stock_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
