# Generated by Django 6.0.6 on 2026-06-18 06:03

import accounts.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='username')),
                ('password', models.CharField(blank=True, default='', max_length=200, verbose_name='password')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('otp_code', models.CharField(blank=True, max_length=5, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('otp_max_try', models.IntegerField(default=5)),
                ('otp_max_out', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام انتخابی')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی تحویل گیرنده')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن تحویل گیرنده')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='شهر')),
                ('postal_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس پستی')),
                ('plaque_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='پلاک')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='واحد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس کاربر',
                'verbose_name_plural': 'آدرس های کاربر',
            },
        ),
    ]
