# Generated by Django 6.0.6 on 2026-06-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_max_try',
            field=models.IntegerField(default=3),
        ),
    ]
