# Generated by Django 6.0.6 on 2026-06-18 06:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cart', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percent', 'درصدی')], max_length=20, verbose_name='نوع تخفیف')),
                ('value', models.PositiveIntegerField(verbose_name='مقدار تخفیف')),
                ('max_discount_toman', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='سقف تخفیف تومان')),
                ('min_order_amount_toman', models.PositiveBigIntegerField(default=0, verbose_name='حداقل مبلغ سفارش تومان')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع اعتبار')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان اعتبار')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='محدودیت استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('code', models.SlugField(allow_unicode=True, max_length=60, unique=True, verbose_name='کد')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=260, verbose_name='توضیحات')),
                ('is_online', models.BooleanField(default=True, verbose_name='پرداخت آنلاین')),
                ('gateway_name', models.CharField(blank=True, max_length=80, verbose_name='نام درگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'روش پرداخت',
                'verbose_name_plural': 'روش\u200cهای پرداخت',
            },
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='کلید سشن')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات سفارش')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('converted', 'تبدیل شده به سفارش'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده')], db_index=True, default='active', max_length=20, verbose_name='وضعیت')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضا')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='cart.cart', verbose_name='سبد خرید')),
                ('selected_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='accounts.useraddress', verbose_name='آدرس انتخاب\u200cشده')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='order.coupon', verbose_name='کد تخفیف')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='order.paymentmethod', verbose_name='روش پرداخت')),
            ],
            options={
                'verbose_name': 'جلسه تکمیل خرید',
                'verbose_name_plural': 'جلسه\u200cهای تکمیل خرید',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='شماره سفارش')),
                ('recipient_full_name', models.CharField(max_length=160, verbose_name='نام گیرنده')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='شماره تماس گیرنده')),
                ('province', models.CharField(blank=True, max_length=80, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='شهر')),
                ('postal_address', models.TextField(verbose_name='آدرس کامل')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='کد پستی')),
                ('subtotal_toman', models.PositiveBigIntegerField(default=0, verbose_name='جمع قیمت کالاها')),
                ('discount_toman', models.PositiveBigIntegerField(default=0, verbose_name='تخفیف')),
                ('tax_toman', models.PositiveBigIntegerField(default=0, verbose_name='مالیات')),
                ('shipping_price_toman', models.PositiveBigIntegerField(default=0, verbose_name='هزینه ارسال')),
                ('total_toman', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ قابل پرداخت')),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('preparing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('cancelled', 'لغو شده'), ('refunded', 'مرجوع شده')], db_index=True, default='pending_payment', max_length=30, verbose_name='وضعیت سفارش')),
                ('payment_status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('pending', 'در انتظار نتیجه پرداخت'), ('paid', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('refunded', 'بازگشت وجه')], db_index=True, default='unpaid', max_length=30, verbose_name='وضعیت پرداخت')),
                ('customer_note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیریت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.useraddress', verbose_name='آدرس کاربر')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.cart', verbose_name='سبد خرید')),
                ('checkout_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='order.checkoutsession', verbose_name='جلسه تکمیل خرید')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.coupon', verbose_name='کد تخفیف')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.paymentmethod', verbose_name='روش پرداخت')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('line_total_toman', models.PositiveBigIntegerField(verbose_name='جمع این کالا')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='product.product', verbose_name='محصول')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='product.productvariant', verbose_name='تنوع محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('amount_toman', models.PositiveBigIntegerField(verbose_name='مبلغ تومان')),
                ('gateway', models.CharField(blank=True, max_length=80, null=True, verbose_name='درگاه پرداخت')),
                ('authority', models.CharField(blank=True, db_index=True, max_length=160, verbose_name='کد authority')),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=160, verbose_name='شماره پیگیری درگاه')),
                ('tracking_code', models.CharField(blank=True, max_length=160, verbose_name='کد رهگیری')),
                ('status', models.CharField(choices=[('initiated', 'شروع شده'), ('pending', 'در انتظار پرداخت'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('refunded', 'برگشت خورده')], db_index=True, default='initiated', max_length=30, verbose_name='وضعیت')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='داده ارسالی')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='داده دریافتی')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تراکنش پرداخت',
                'verbose_name_plural': 'تراکنش\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
    ]
