# Generated by Django 6.0.6 on 2026-06-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام محصول در زمان سفارش'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price_toman',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت واحد در زمان سفارش'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_summary',
            field=models.CharField(blank=True, help_text='مثلاً: ۲۵۰ گرم • آسیاب متوسط', max_length=255, verbose_name='مشخصات تنوع در زمان سفارش'),
        ),
    ]
