# Generated by Django 6.0.6 on 2026-06-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_product_title_orderitem_unit_price_toman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_tracking_code',
            field=models.CharField(blank=True, max_length=120, verbose_name='کد پیگیری پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method_title',
            field=models.CharField(blank=True, default='روش امن', max_length=120, verbose_name='روش ارسال'),
        ),
    ]
