# Generated by Django 6.0.6 on 2026-06-21 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('order', '0003_order_payment_tracking_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='selected_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='accounts.useraddress', verbose_name='آدرس انتخاب\u200cشده'),
        ),
    ]
